version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://d5624c6be397fc4c3edf93df77224f8ad25de11129b418980e397a27470cba42:sk_JGLEPMXk_Yeim1atFjyoW@db.prisma.io:5432/postgres?sslmode=require
      - JWT_SECRET=abcd
    depends_on:
      - db
    networks:
      - app-network

  studio:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgres://d5624c6be397fc4c3edf93df77224f8ad25de11129b418980e397a27470cba42:sk_JGLEPMXk_Yeim1atFjyoW@db.prisma.io:5432/postgres?sslmode=require
    ports:
      - "5555:5555"
    command: >
      sh -c "
        npm install -g prisma &&
        npx prisma migrate dev --name init --preview-feature-flag 
        npx prisma studio --port 5555 --browser none
      "
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: feedback_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
